#!/bin/nano
//! this file is automatically generated by `manage.sh` script you can edit this and this isn't overwrited but better is rewriting with this script using `manage.sh --boot-config`
//! vga default
pub const HEIGHT: usize = 25;
pub const WIDTH: usize = 80;

// terminal
pub const BUFFER_LEN: usize = WIDTH * HEIGHT * 10;
pub const DEFAULT_COLOR: u8 = 0x07;
pub const HIGHTLIGHT_COLOR: u8 = 0x0f;

// panic
pub const PANIC_COLOR: u8 = 0xcf;
