#!/bin/nano
//! this file is automatically generated by `manage.sh` script. You can edit this and this isn't overwrited but easier is rewriting with this script using `./manage.sh --boot-config`
// vga default

/// vga text mode lines
pub const HEIGHT: usize = 25;
/// vga text mode columns
pub const WIDTH: usize = 80;

// terminal
/// terminal buffer length
pub const BUFFER_LEN: usize = WIDTH * HEIGHT * 10;
/// default terminal color
pub const DEFAULT_COLOR: u8 = 0x07;
/// default terminal hightlight color
pub const HIGHTLIGHT_COLOR: u8 = 0x0f;
/// lines scrolled per press
pub const SCROLL_PER_PRESS: usize = 7;

// panic
/// panic color
pub const PANIC_COLOR: u8 = 0xcf;

// device
/// maximum devices
pub const DEVICES: usize = 15;
/// maximum size of device writable object
pub const MAX_DEV_OUT: usize = 8;
/// buffer size of every device
pub const DEV_BUFFER: usize = 8;

// utility
/// Str size
pub const STR_SIZE: usize = 256;
