#!/bin/nano
// file generated by `manage.py` script

pub mod acpi;
pub mod system_core;
pub mod core_lib;
pub mod ps2;
pub mod vga;

pub fn early_init() {


}

pub fn init() {

	ps2::init();
	vga::init();

}

pub fn shutdown() {


}

pub fn stop_machine() {

	acpi::stop_machine();

}

pub fn reboot_machine() {

	acpi::reboot_machine();

}

pub fn panic() {


}

pub fn timer_int() {

	ps2::timer_int();

}

pub fn keyboard_int() {

	ps2::keyboard_int();

}

pub fn mouse_int() {

	ps2::mouse_int();

}

