#!/bin/nano
[package]
name = "nierdzewny"
version = "0.1.0"
authors = ["TANDEX"]
edition = "2018"
description = "boot for nierdzewny operating system"

[dependencies]
bootloader = "0.9.13"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
