#!/bin/nano
//! this file is automatically generated by `manage.sh` script. You should not edit this file, generate it by `./manage.sh --mods` or by `./manage.sh --specify-mods`

pub mod acpi;
pub mod ps2;
pub mod vga_text;

/// modules early init, first thing that boot do
pub fn early_init() {

	vga_text::early_init();

}

/// modules init, initianize modules after most important things
pub fn init() {

	ps2::init();

}

/// modules shutdown, function called on system shutdown
pub fn shutdown() {


}

/// modules machine stop, function for shutdown system
pub fn stop_machine() {

	acpi::stop_machine();

}

/// modules machine reboot, function for reboot system
pub fn reboot_machine() {

	acpi::reboot_machine();

}

/// modules keyboard interrupt, called when keyboard interrupt arrives, used for keyboard input
pub fn keyboard_int() {

	ps2::keyboard_int();

}

/// modules timer interrupt, function called on timer interrupt
pub fn timer_int() {

	ps2::timer_int();

}
